# Generated by Django 4.2.10 on 2024-02-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
